---
- name: create chronos tasks
  uri: >
    url="{{ chronos_url }}/scheduler/{{ item.type }}"
    method=POST
    HEADER_Content-Type="application/json"
    body='{{ item.app | to_json }}'
    status_code=204
  with_items: chronos_tasks
